FROM ghcr.io/linuxserver/baseimage-selkies:arm64v8-ubunturesolute

# set version label
ARG BUILD_DATE
ARG VERSION
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="thelamer"

# title
ENV TITLE="Ubuntu MATE"

RUN \
  echo "**** add icon ****" && \
  curl -o \
    /usr/share/selkies/www/icon.png \
    https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/webtop-logo.png && \
  echo "**** install packages ****" && \
  add-apt-repository ppa:xtradeb/apps && \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive \
  apt-get install --no-install-recommends -y \
    7zip \
    atril \
    ayatana-indicator-application \
    caja-open-terminal \
    caja-rename \
    caja-sendto \
    caja-wallpaper \
    chromium \
    engrampa \
    eom \
    fonts-liberation \
    mate-applets \
    mate-applet-brisk-menu \
    mate-calc \
    mate-system-monitor \
    mate-terminal \
    mozo \
    pluma \
    ubuntu-mate-artwork \
    ubuntu-mate-default-settings \
    ubuntu-mate-desktop \
    ubuntu-mate-icon-themes && \
  echo "**** mate tweaks ****" && \
  sed -i \
    's#^Exec=.*#Exec=/usr/local/bin/wrapped-chromium#g' \
    /usr/share/applications/chromium.desktop && \
  rm -f \
    /etc/xdg/autostart/mate-power-manager.desktop \
    /etc/xdg/autostart/mate-screensaver.desktop \
    /usr/bin/mate-screensaver \
    /usr/share/dbus-1/services/org.knopwob.dunst.service \
    /usr/share/dbus-1/services/org.mate.ScreenSaver.service && \
  echo "**** cleanup ****" && \
  apt-get autoclean && \
  rm -rf \
    /config/.cache \
    /config/.launchpadlib \
    /usr/share/gvfs/remote-volume-monitors/* \
    /var/lib/apt/lists/* \
    /var/tmp/* \
    /tmp/*

# add local files
COPY /root /

# ports and volumes
EXPOSE 3000
VOLUME /config
