[General]
__userfile__=true
icon_follow_color_scheme=true
icon_theme=Papirus-Dark
theme=ambiance

[Palette]
base_color=#595a5a
highlight_color=#c9cbcb
highlighted_text_color=#3f3f3f
link_color=#49daf0
link_visited_color=#c745d3
text_color=#ececec
window_color=#636464
window_text_color=#f9f9f9
