# Based on the issue template
name: Feature request
description: Suggest an idea for this project
title: "[FEAT] <title>"
labels: [enhancement]
body:
  - type: checkboxes
    attributes:
      label: Is this a new feature request?
      description: Please search to see if a feature request already exists.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Wanted change
      description: Tell us what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reason for change
      description: Justify your request, why do you want it, what is the benefit.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed code change
      description: Do you have a potential code change in mind?
    validations:
      required: false
