[General]
icon_theme=breeze
theme=selkies

[Palette]
window_color=#120724
window_text_color=#F2EEFB
base_color=#0C0318
text_color=#F2EEFB
highlight_color=#AE3F7E
highlighted_text_color=#FFFFFF
link_color=#46E5E5
link_visited_color=#7967C5
tooltip_base_color=#1C0E38
tooltip_text_color=#F2EEFB

[Qt]
style=Fusion
