panels=panel1

[panel1]
plugins=fancymenu, quicklaunch, taskbar, statusnotifier, tray, volume, clock, showdesktop
position=Bottom
desktop=0

[fancymenu]
type=fancymenu
alignment=Left
icon=/usr/share/lxqt/themes/selkies/mainmenu.svg
filterClear=true
autoSel=true
autoSelDelay=150

[quicklaunch]
type=quicklaunch
alignment=Left
apps\size=3
apps\1\desktop=/usr/share/applications/chromium.desktop
apps\2\desktop=/usr/share/applications/qterminal.desktop
apps\3\desktop=/usr/share/applications/pcmanfm-qt.desktop

[taskbar]
type=taskbar
buttonWidth=220
closeOnMiddleClick=true
groupingEnabled=false

[statusnotifier]
type=statusnotifier
alignment=Right

[tray]
type=tray

[volume]
type=volume
device=0

[clock]
type=clock

[showdesktop]
type=showdesktop
alignment=Right
